version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=${REPO_ECR}
      - DOCKERHUB_USERNAME=${DH_USERNAME}
      - DOCKERHUB_PASSWORD=${DH_PASSWORD}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=prod-${COMMIT_HASH:=latest}-$CODEBUILD_START_TIME
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - docker push $REPOSITORY_URI:$IMAGE_TAG