export const customCss = (data: any) =>
  `/* Document
   ========================================================================== */
   
/*
    Styles generated by mycheckout
*/
._kuikpay-myCheckout-styles-module__Checkoutless
  ._kuikpay-myCheckoutButton__myCheckoutButtonContainer
  ._kuikpay-myCheckoutButton__myCheckoutButtonText {
    color: ${data.button.normal.textColor};
    font-family: ${data.button.font};
  }

._kuikpay-myCheckout-styles-module__Checkoutless
  ._kuikpay-myCheckoutButton__myCheckoutButtonContainer:hover
  ._kuikpay-myCheckoutButton__myCheckoutButtonText {
    color: ${data.button.hover.textColor};
  }

._kuikpay-myCheckout-styles-module__Checkoutless
  ._kuikpay-myCheckoutButton__myCheckoutButtonContainer
  ._kuikpay-myCheckoutButton__myCheckoutButtonContent {
    background-color: ${data.button.normal.backgroundColor};
    border: 1px solid ${data.button.normal.outlineColor};
    border-radius: ${data.button.borderRadius}px;
    width: ${data.button.width}%;
  }
  
._kuikpay-myCheckout-styles-module__Checkoutless
  ._kuikpay-myCheckoutButton__myCheckoutButtonContainer
  ._kuikpay-myCheckoutButton__myCheckoutButtonContent:hover {
    background-color: ${data.button.hover.backgroundColor};
    border: 1px solid ${data.button.hover.outlineColor};
    border-radius: ${data.button.borderRadius}px;
  }
  

._kuikpay-myCheckout-styles-module__Checkoutless p,
._kuikpay-myCheckout-styles-module__Checkoutless a,
._kuikpay-myCheckout-styles-module__Checkoutless div,
._kuikpay-myCheckout-styles-module__Checkoutless input,
._kuikpay-myCheckout-styles-module__Checkoutless select {
  font-family: ${data.modal.font};
}

._kuikpay-myCheckout-styles-module__Checkoutless
  ._kuikpay-modal__modalContainer {
    background-color: ${data.modal.backgroundColor};
}

._kuikpay-myCheckout-styles-module__Checkoutless
  ._kuikpay-input__inputContent 
  ._kuikpay-input__input {
    background-color: ${data.modal.backgroundColor};
}

._kuikpay-myCheckout-styles-module__Checkoutless
  ._kuikpay-button__buttonContent 
  ._kuikpay-button__buttonContainer {
    background-color: ${data.modal.button.normal.backgroundColor};
    border: 1px solid ${data.modal.button.normal.outlineColor};
    color: ${data.modal.button.normal.textColor};
    border-radius: ${data.modal.button.borderRadius}px;
}

._kuikpay-myCheckout-styles-module__Checkoutless 
  ._kuikpay-button__buttonContent 
  ._kuikpay-button__buttonContainer:hover {
    background-color: ${data.modal.button.hover.backgroundColor};
    border: 1px solid ${data.modal.button.hover.outlineColor};
    color: ${data.modal.button.hover.textColor};
    border-radius: ${data.modal.button.borderRadius}px;
}

._kuikpay-myCheckout-styles-module__Checkoutless
  ._kuikpay-button__buttonContent 
  ._kuikpay-button__buttonContainer[disabled] {
    border: 1px solid #919191;
    background-color: #ffffff;
    color: #919191;
}

._kuikpay-myCheckout-styles-module__Checkoutless
  ._kuikpay-myCheckout-styles-module__iconAlternative {
    fill: ${data.modal.icons.color};
}`;
